name: API Testing Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Execute Tests
        run: mvn clean test -Dsuite=suite -X

      - name: Upload Logs
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Logs
          path: logs/

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: TestNG Results
          path: target/surefire-reports/junitreports/TEST-*.xml
          reporter: java-junit
